version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: spring_batch
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8080:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    postgres-data:
    pgadmin_data: