rootProject.name = "spring-batch-demo"
include("par-ou-impar-job")
include("arquivo-delimitado-job")
include("arquivo-largura-fixa-job")
include("ola-job")
include("arquivo-multiplos-formatos-job")
include("jdbc-cursor-job")
include("jdbc-paging-job")
include("skip-error-job")
include("processador-validacao")
include("processador-classificador")
include("arquivo-flat-customizado-job")
include("jdbc-writer-job")