spring:
    application:
        name: spring-batch-demo
    datasource:
        url: jdbc:postgresql://localhost:5432/spring_batch
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
    batch:
        job:
            name: demonstrativoOrcamentarioJob
        jdbc:
            initialize-schema: always